urls:
  base_url: https://github.com/sekoyatech/mobile-app-pages  # https://sekoya.tech
  contact: /contact                                         # /contact
  about-us: /about-us                                       # /about-us
  privacy-policy: /privacy-policy                           # /privacy-policy
  terms-of-service: /terms-of-service                       # /terms-of-service
  faq: /faq                                                 # /faq
  gdpr: /gdpr                                               # /gdpr